### ISSUE TITLE
Swrve sqlite exception

### ISSUE THREAD

**Issue by Hari199** [Swrve/swrve-android-sdk#276]
Hi, 

The following exception i am getting after integrating Swrve sdk

 Exception setting cache for userId:8cec0687-1e9c-4232-ace8-90c5124f88e4 category:RegistrationId rawData:dhHV5trQAB4:APA91bGnqBUVM0uBv4LJVgHVme6wxtit4VqVRT4VcS4T75FwJ8I2a_4eHBKtH-ZQFg1mgDbviCbnr37amqdgFlRVultVb8S1J_ZPUGvjow4EvS-m4hU5NW9PDPKMUsZ31f4qbUt9grHJ
                                                                                android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database - SQLITE_READONLY_CANTLOCK (Sqlite code 1032), (OS error - 2:No such file or directory)
                                                                                    at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                                    at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:818)
                                                                                    at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:803)
                                                                                    at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                                    at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1727)
                                                                                    at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1619)
                                                                                    at com.swrve.sdk.localstorage.SQLiteLocalStorage.insertOrUpdate(SQLiteLocalStorage.java:131)
                                                                                    at com.swrve.sdk.localstorage.SQLiteLocalStorage.setCacheEntry(SQLiteLocalStorage.java:115)
                                                                                    at com.swrve.sdk.localstorage.SwrveMultiLayerLocalStorage.setCacheEntry(SwrveMultiLayerLocalStorage.java:154)
                                                                                    at com.swrve.sdk.Swrve._setRegistrationId(Swrve.java:134)
                                                                                    at com.swrve.sdk.Swrve.access$000(Swrve.java:21)
                                                                                    at com.swrve.sdk.Swrve$1.doInBackground(Swrve.java:49)
                                                                                    at com.swrve.sdk.Swrve$1.doInBackground(Swrve.java:42)
                                                                                    at android.os.AsyncTask$2.call(AsyncTask.java:316)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                    at java.lang.Thread.run(Thread.java:776)

How to resolve this ??

Thanks

**Comment by dominicmarmionswrve** [comment]
@Hari199 Thanks for letting us know. Which version of swrvesdk are you using and was this exception happening consistently or only on a particular device or OS version?

**Comment by Hari199** [comment]
I am using  api 'com.swrve.sdk.android:swrve-firebase:5.2.0' 
I have tested in two devices with android version 6 and 7. Both have this issue and it happens consistently.

Thanks

**Comment by dominicmarmionswrve** [comment]
Thanks, we will investigate and get back to you.

**Comment by dominicmarmionswrve** [comment]
@Hari199 I've spent some time trying to reproduce but am unable. Its difficult to debug without knowing more about your particular configuration. Could you share anymore details? Perhaps, another third party library is wiping the database as suggested by this [post](https://stackoverflow.com/questions/35090893/sqlitereadonlydatabaseexception-attempt-to-write-a-readonly-database-code-1032)?

Ideally, could you create an empty project that reproduces the issue and share it here as a zip?

**Comment by Hari199** [comment]
@dominicmarmionswrve , After downgrading the sdk version i am not getting that exception.

**Comment by dominicmarmionswrve** [comment]
Hi @Hari199, thanks for getting back and your patience. Which version did you downgrade to? Was it 5.1.1? 

We are still stumped on how to reproduce. We would really appreciate if you could help us get to the bottom of this. I've attached a Firebase Demo project. Could you check if the issue occurs on that project? Just change the google-services.json file to your own version and change the applicationId in the build.gradle to your own also.

I've tested using android emulator on version 6/7/8 and it works fine. Have you been using real device or emulator?

Any other steps or info you can give us? If you have a reproducible project, could you share please?

[SwrveSDKDemo.zip](https://github.com/Swrve/swrve-android-sdk/files/1947328/SwrveSDKDemo.zip)

**Comment by Hari199** [comment]
Hi @dominicmarmionswrve , I am using  api 'com.swrve.sdk.android:swrve-firebase:5.0.0'. Actually i have a library project in which i have added this. I have tested it in real device with android 7.0.

**Comment by dominicmarmionswrve** [comment]
Ok, I've tested using the zip I attached earlier on Samsung s6 running api 7.0, and the swrve firebase sdk 5.2, and it works fine.

Could you try out that zipped project please? It should be really quick. All you have to do is:
- replace google-services.json with your own version
- change the applicationId in build.gradle to your own package name
- Change the YOUR_APP_ID and YOUR_API_KEY in DemoApplication.java to your app details.

This would help greatly in figuring out is it a configuration issue in your project or some a bug in the sdk. 

One final question, does the exception cause a crash?

**Comment by Hari199** [comment]
Hi @dominicmarmionswrve, I have tested the demo project that you share and it doesn't show any exception. But when i copy and paste the same code in my project it gives exception. It is not crashing. Even sdk version 5.0 now causing the issue. Additionally i am also using sqlite in my app also. 

I find this from sqlite official website

The SQLITE_READONLY_CANTLOCK error code is an extended error code for SQLITE_READONLY. The SQLITE_READONLY_CANTLOCK error code indicates that SQLite is unable to obtain a read lock on a WAL mode database because the shared-memory file associated with that database is read-only.

Thanks

**Comment by dominicmarmionswrve** [comment]
Are you setting the database name in your config via the setDbName method?

**Comment by Hari199** [comment]
No, i am not doing anything. I am just using the same config as it is in demo project.

**Comment by dominicmarmionswrve** [comment]
:( I was hopeful that was it! Back to the drawing board!

I know the chances of this are close to zero, but are you using a database name for your own sqlite db called "swrve.db"? If we're both using the same database name then possibly we're both trying to write at the same time while one of us has a lock on the db.

Are you using any database helper libraries such as SQLCipher, or any ORM library?

Could you share a list of the libraries you use?

**Comment by Hari199** [comment]
api 'com.google.code.gson:gson:2.8.1'
    api files('libs/glide-3.6.1.jar')
    api 'com.android.volley:volley:1.1.0'
    api 'com.squareup.picasso:picasso:2.5.2'
    api 'com.android.support:appcompat-v7:27.1.0'
    api 'com.android.support:recyclerview-v7:27.1.0'
    api 'com.android.support:mediarouter-v7:27.1.0'
    api 'com.google.android.gms:play-services-cast-framework:15.0.0'
    api 'io.branch.sdk.android:library:2.16.0'
    api project(path: ':EXO2PROJECT')
    api 'com.swrve.sdk.android:swrve-firebase:5.0.0'
    api 'com.squareup.okhttp3:okhttp:3.5.0'
    api 'com.google.firebase:firebase-core:15.0.0'
    api 'com.google.firebase:firebase-messaging:15.0.0'

These are the libraries i am using in my project . Not using any external database libraries.

No, i have a different database name :-)

**Comment by dominicmarmionswrve** [comment]
Thanks again for your help and your patience with this. We're truly stumped with it. If we could reproduce we should be able to resolve. Could you please send us a stripped down version of your project so we can reproduce? I am confident we can solve this.

**Comment by dominicmarmionswrve** [comment]
Hi @Hari199, is this error still occurring for you?

**Comment by dominicmarmionswrve** [comment]
Closing this as unable to reproduce and inactive for a long time.
