### ISSUE TITLE
WindowLeaked and NullPointerException on sdk 4.0.1

### ISSUE THREAD

**Issue by Rloguzzo** [Swrve/swrve-android-sdk#40]
Hi.
1. activate the option to destroy activities in the debug settings
2. activate an event with a in-app message.
3. Pressing the home button.
4. relaunch the activity.

 E/WindowManager﹕ android.view.WindowLeaked: Activity "the activity" has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{8c0dc47 V.E..... R.....I. 0,0-1080,1776} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
            at android.app.Dialog.show(Dialog.java:298)
            at com.swrve.sdk.SwrveImp$DisplayMessageRunnable.run(SwrveImp.java:1338)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

and then starts throwing many NullPointerExceptions 

E/SwrveSDK﹕ Exception thrown in Swrve SDK
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set com.swrve.sdk.SwrveBase.getAssetsOnDisk()' on a null object reference
            at com.swrve.sdk.messaging.SwrveMessage.assetInCache(SwrveMessage.java:199)
            at com.swrve.sdk.messaging.SwrveMessage.isDownloaded(SwrveMessage.java:215)
            at com.swrve.sdk.messaging.SwrveCampaign.getNextMessage(SwrveCampaign.java:154)
            at com.swrve.sdk.messaging.SwrveCampaign.getMessageForEvent(SwrveCampaign.java:118)
            at com.swrve.sdk.SwrveBase._getMessageForEvent(SwrveBase.java:946)
            at com.swrve.sdk.SwrveBase.getMessageForEvent(SwrveBase.java:1596)
            at com.swrve.sdk.messaging.SwrveEventListener.onEvent(SwrveEventListener.java:49)
            at com.swrve.sdk.SwrveImp.queueEvent(SwrveImp.java:439)
            at com.swrve.sdk.SwrveImp.queueEvent(SwrveImp.java:432)
            at com.swrve.sdk.SwrveBase._event(SwrveBase.java:309)
            at com.swrve.sdk.SwrveBase.event(SwrveBase.java:1372)
            at com.swrve.sdk.SwrveBase._event(SwrveBase.java:302)
            at com.swrve.sdk.SwrveBase.event(SwrveBase.java:1363)
            at com.swrve.sdk.SwrveSDKBase.event(SwrveSDKBase.java:63)

**Comment by Sergio-Mira** [comment]
Thanks @Rloguzzo we'll have a look at reproducing the problem and fixing it

**Comment by Sergio-Mira** [comment]
Hi @Rloguzzo I haven't been able to reproduce the problem. It looks like the dialog was not dismissed in your case. For the SDK to do that you have to instrument in your activities the following hooks:
onCreate, onPause, onResume, onNewIntent, onDestroy

Let us know if that was the case and how it goes!

**Comment by Rloguzzo** [comment]
Hi, @Sergio-Mira, we have correctly implemented the sdk.
You have activated the option Don't keep activities in developer options?
Jason Turbin sent me a sample application on fragments and in-app messages in the application and this also happens

**Comment by Sergio-Mira** [comment]
Hi @Rloguzzo we were able to reproduce the NPE (not the window leak unfortunately) with the code that Jason sent you and we've have a fix ready. We will release the fix in an upcoming hotfix we have planned and let you know here. Thanks!
https://github.com/Swrve/swrve-android-sdk/commit/52b28015145928c2faa7bc46a571921d72f01cdd

**Comment by Sergio-Mira** [comment]
The fix is out in 4.0.2 released yesterday. Let us know if the issue comes up again. Thanks!
